name: flutter_my_portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.2
  equatable: 2.0.5
  flutter_screenutil: 5.8.4
  shared_preferences: 2.2.2
  easy_localization: 3.0.5
  location: 4.4.0
  logger: 2.1.0
  flutter_form_builder: 9.1.0
  expandable: 5.0.1
  http: 1.1.0
  carousel_slider: 4.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/clone/
